/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostsPostsImport } from './routes/_posts/posts'
import { Route as PostsPostsPostIdImport } from './routes/_posts/posts.$postId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostsRoute = PostsPostsImport.update({
  id: '/_posts/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostsPostIdRoute = PostsPostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsPostsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_posts/posts': {
      id: '/_posts/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsPostsImport
      parentRoute: typeof rootRoute
    }
    '/_posts/posts/$postId': {
      id: '/_posts/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostsPostIdImport
      parentRoute: typeof PostsPostsImport
    }
  }
}

// Create and export the route tree

interface PostsPostsRouteChildren {
  PostsPostsPostIdRoute: typeof PostsPostsPostIdRoute
}

const PostsPostsRouteChildren: PostsPostsRouteChildren = {
  PostsPostsPostIdRoute: PostsPostsPostIdRoute,
}

const PostsPostsRouteWithChildren = PostsPostsRoute._addFileChildren(
  PostsPostsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsPostsRouteWithChildren
  '/posts/$postId': typeof PostsPostsPostIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsPostsRouteWithChildren
  '/posts/$postId': typeof PostsPostsPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_posts/posts': typeof PostsPostsRouteWithChildren
  '/_posts/posts/$postId': typeof PostsPostsPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/posts' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/posts' | '/posts/$postId'
  id: '__root__' | '/' | '/about' | '/_posts/posts' | '/_posts/posts/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostsPostsRoute: typeof PostsPostsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsPostsRoute: PostsPostsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/_posts/posts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_posts/posts": {
      "filePath": "_posts/posts.tsx",
      "children": [
        "/_posts/posts/$postId"
      ]
    },
    "/_posts/posts/$postId": {
      "filePath": "_posts/posts.$postId.tsx",
      "parent": "/_posts/posts"
    }
  }
}
ROUTE_MANIFEST_END */
